.\" Copyright (c) 2009-2014 Roy Marples
.\" All rights reserved
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd September 16, 2014
.Dt DHCPCD-GTK 8
.Os
.Sh NAME
.Nm dhcpcd-gtk
.Nd a GTK+ frontend for network configuration
.Sh DESCRIPTION
.Nm
is a GTK+ frontend for network configuration.
It uses
.Xr dhcpcd 8
and
.Xr wpa_supplicant 8
as backends.
.Pp
If
.Nm
is used to make configuration changes then the user needs to be able
to write to the privileged
.Nm dhcpcd
control socket.
See
.Xr dhcpcd.conf 5
for details.
.Ss wpa_supplicant
.Nm
relies on
.Xr wpa_supplicant 8
being configured to write its sockets to
.Pa /var/run/wpa_supplicant.
If 
.Nm
is used to select and set pass phrases for wireless networks then
update_config=1
needs to be set in wpa_supplicant.conf.
.Sh SEE ALSO
.Xr dhcpcd 8 ,
.Xr dhcpcd.conf 5 ,
.Xr wpa_supplicant 8 ,
.Xr wpa_supplicant.conf 5
.Sh AUTHORS
.An Roy Marples Aq roy@marples.name
.Sh BUGS
Please report them to http://roy.marples.name/projects/dhcpcd-ui
